# Generated by Django 3.1.2 on 2020-10-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Contact_Tel',
            new_name='areacode',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Your_Feedback',
            new_name='feedback',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='First_Name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Last_Name',
            new_name='lname',
        ),
        migrations.AddField(
            model_name='contact',
            name='telnum',
            field=models.CharField(default='10000', max_length=122),
        ),
    ]
