# Generated by Django 3.1.2 on 2020-10-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201016_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
